Address pickle error
Trying to pickle the entire Experiment object would lead to this
runtime error:

TypeError: can't pickle SwigPyObject objects

I think this is because Experiment included the equilibrium_simulator...